[tools]
"elixir" = "1.18.3"
"erlang" = "26.2.5"
"ubi:orhun/git-cliff" = "2.8.0"
"zig" = "0.14.0"
"sops" = "3.10.1"
"age" = "1.2.1"
"pnpm" = "10.11.0"
"nodejs" = "22.14.0"
"npm:wrangler" = "4.4.0"

[env]
_.file = ".env.json"

[hooks]
postinstall = ["mise run install"]

[settings]
sops.age_key_file = "~/.config/mise/plasma-age.txt"
