name: Agent

on:
  push:
    branches:
      - main
  pull_request:
  merge_group: {}

concurrency:
  group: agent-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test
  MISE_EXPERIMENTAL: 1
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Restore Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            agent/deps
            agent/_build
            agent/_site
          key: mix-agent-${{ hashFiles('agent/mix.lock') }}
      - run: mise run agent:lint
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Restore Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            agent/deps
            agent/_build
            agent/_site
          key: mix-agent-${{ hashFiles('agent/mix.lock') }}
      - run: mise run agent:test
