name: Docs Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: docs-deployment-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: 1
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  cloudflare:
    name: Cloudflare
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run docs:deploy
