name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version (macOS only)
      if: matrix.os == 'macos-latest'
      run: sudo xcode-select -s /Applications/Xcode_16.0.app
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftFormat
      run: |
        git clone https://github.com/nicklockwood/SwiftFormat
        cd SwiftFormat
        swift build -c release
        sudo cp .build/release/swiftformat /usr/local/bin/
    
    - name: Check formatting
      run: swiftformat --lint .